function Game() {
  this.playersGuess = null;
  this.pastGuesses = [];
  this.winningNumber = generateWinningNumber();
}

Game.prototype.playersGuessSubmission = function(guess) {
  if (guess < 1 || guess > 100 || isNaN(guess)) {
    throw 'That is an invalid guess.';
  }

  this.playersGuess = guess;

  return this.checkGuess();
};

Game.prototype.checkGuess = function() {
  if (this.playersGuess === this.winningNumber) {
    $('#hint, #submit').attr('disabled', true);
    $('#subtitle').text('Click the reset button!');
    return 'You Win!';
  }

  if (this.pastGuesses.includes(this.playersGuess)) {
    return 'You have already guessed that number.';
  }

  this.pastGuesses.push(this.playersGuess);
  $('#guess-list li:nth-child(' + this.pastGuesses.length + ')').text(
    this.playersGuess
  );

  if (this.pastGuesses.length === 5) {
    $('#hint, #submit').attr('disabled', true);
    $('#subtitle').text('Click the reset button!');
    return 'You Lose.';
  }

  var diff = this.difference();
  if (this.isLower()) {
    $('#subtitle').text('Guess higher.');
  } else {
    $('#subtitle').text('Guess lower.');
  }

  if (this.difference() < 10) {
    return "You're burning up!";
  }

  if (this.difference() < 25) {
    return "You're lukewarm.";
  }

  if (this.difference() < 50) {
    return "You're a bit chilly.";
  }

  if (this.difference() < 100) {
    return "You're ice cold!";
  }
};

Game.prototype.difference = function() {
  let result = this.winningNumber - this.playersGuess;
  return result > 0 ? result : -result;
};

Game.prototype.isLower = function() {
  return this.playersGuess < this.winningNumber;
};

Game.prototype.provideHint = function() {
  return shuffle([
    this.winningNumber,
    generateWinningNumber(),
    generateWinningNumber()
  ]);
};

function newGame() {
  return new Game();
}

function generateWinningNumber() {
  return Math.floor(Math.random() * 100) + 1;
}

function shuffle(arr) {
  let index = arr.length;
  let randomIndex;
  let temp;

  while (--index > 0) {
    randomIndex = Math.floor(Math.random() * (index + 1));
    temp = arr[randomIndex];
    arr[randomIndex] = arr[index];
    arr[index] = temp;
  }

  return arr;
}

$(document).ready(() => {
  // create a new game instance
  let game = newGame();

  $('#submit').on('click', e => {
    // extract the value from the input
    let playerInput = $('#player-input').val();
    // clear the input element
    $('#player-input').val('');
    let result = game.playersGuessSubmission(playerInput);
    $('#title').text(result);
  });

  $('#player-input').keypress(e => {
    if (e.which == 13) {
      $('#submit').click();
    }
  });

  $('#hint').on('click', e => {
    // show the three list options generated by your provideHint function
    let hint = game.provideHint();
    $('#hints').text(`Hint: ${hint[0]}, ${hint[1]}, ${hint[2]}`);
    $('#hint').attr('disabled', true);
  });

  $('#reset').on('click', e => {
    // create a new game instance
    game = newGame();

    // reset the #title and #subtitle
    $('#title').text('Guessing Game');
    $('#subtitle').text('Guess a number between 1-100.');
    $('.guess').text('x');

    // renable #submit and #hint buttons
    $('#hint, #submit').attr('disabled', false);
  });
});
